<?xml version="1.0" encoding="windows-1252"?>
<xsl:stylesheet	xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0"
				xmlns:assignments="http://www.iana.org/assignments">
	<xsl:output method="text" encoding="windows-1252"/>
	<xsl:template match="/assignments:registry">
		<xsl:variable name="version" select="'200'"/>
		<xsl:text>/* Generated by character-sets.rc.xsl */&#xa;</xsl:text>
		<xsl:text>#include &lt;windows.h&gt;&#xa;&#xa;</xsl:text>
		<xsl:text>LANGUAGE LANG_NEUTRAL, SUBLANG_NEUTRAL&#xa;</xsl:text>
		<xsl:text>VS_VERSION_INFO VERSIONINFO&#xa;</xsl:text>
		<xsl:text>	FILEVERSION     </xsl:text>
		<xsl:value-of select="translate(concat($version, '-', assignments:updated), '-', ',')"/>
		<xsl:text>&#xa;</xsl:text>
		<xsl:text>	PRODUCTVERSION  </xsl:text>
		<xsl:value-of select="translate(concat($version, '-', assignments:updated), '-', ',')"/>
		<xsl:text>&#xa;</xsl:text>
		<xsl:text>	FILEOS          VOS_NT_WINDOWS32&#xa;</xsl:text>
		<xsl:text>	FILETYPE        VFT_DLL&#xa;</xsl:text>
		<xsl:text>{&#xa;</xsl:text>
		<xsl:text>	BLOCK "StringFileInfo"&#xa;</xsl:text>
		<xsl:text>	{&#xa;</xsl:text>
		<xsl:text>		BLOCK "000004B0"&#xa;</xsl:text>
		<xsl:text>		{&#xa;</xsl:text>
		<xsl:text>			VALUE "Comments", "Free for corporate and personal use."&#xa;</xsl:text>
		<xsl:text>			VALUE "CompanyName", "Jochen Neubeck"&#xa;</xsl:text>
		<xsl:text>			VALUE "FileDescription", "character-sets.dll"&#xa;</xsl:text>
		<xsl:text>			VALUE "FileVersion", "</xsl:text>
		<xsl:value-of select="translate(concat($version, '-', assignments:updated), '-', '.')"/>
		<xsl:text>"&#xa;</xsl:text>
		<xsl:text>			VALUE "LegalCopyright", "© 2015-2017 Jochen Neubeck"&#xa;</xsl:text>
		<xsl:text>		}&#xa;</xsl:text>
		<xsl:text>	}&#xa;</xsl:text>
		<xsl:text>	BLOCK "VarFileInfo"&#xa;</xsl:text>
		<xsl:text>	{&#xa;</xsl:text>
		<xsl:text>		VALUE "Translation", 0x0000, 0x04B0&#xa;</xsl:text>
		<xsl:text>	}&#xa;</xsl:text>
		<xsl:text>}&#xa;</xsl:text>
	</xsl:template>
	<xsl:template match="*">
	</xsl:template>
</xsl:stylesheet>